name: Deploy to Firebase Hosting

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install Firebase Tools
        run: npm install -g firebase-tools
      
      - name: Create Service Account File
        env:
          FIREBASE_KEY: ${{ secrets.FIREBASE_TOKEN }}
        run: echo "$FIREBASE_KEY" > ./firebase-key.json
      
      - name: Deploy to Firebase
        run: |
          firebase deploy --project lojas-uniso --key-file ./firebase-key.json
